### ISSUE TITLE
Handle verification fails if handle is mixed case

### ISSUE THREAD

**Issue by qxtal** [furSUDO/simple-atproto-handles#2]
On my instance, I've had some users reporting that their handles fail to get verified on Bluesky if the newly-created handle contains mixed/upper case characters. Manually changing the database entries to be fully lower-case fixes the issues those users had with Bluesky's verification process.

Whether or not this is an error on Bluesky's implementation of handle verifications, a simple fix for now would be to force handles to be saved as lower-case only.

**Comment by furSUDO** [comment]
Thank you for the issue @qxtal,
This was fixed in the upstream branch, but never made it's way to the template (Now fixed in commit: https://github.com/furSUDO/simple-atproto-handles/commit/369fafbceec568b0feca98998241a4186638c92e)
